In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder, StandardScaler
import torch
pd.set_option('display.max_columns', None)

In [2]:
dataPath = "data/"

pairs = pd.read_csv(dataPath + "relation.csv")
users = pd.read_csv(dataPath + "customers.csv", index_col="id")
items = pd.read_csv(dataPath + "products.csv", index_col="id")


/tmp/ipykernel_1068/1774659839.py:4: DtypeWarning: Columns (7,9,10,11,12,13,17,18,21,26,27,28,30,36) have mixed types. Specify dtype option on import or set low_memory=False.
  users = pd.read_csv(dataPath + "customers.csv", index_col="id")
/tmp/ipykernel_1068/1774659839.py:5: DtypeWarning: Columns (20,32,34,39) have mixed types. Specify dtype option on import or set low_memory=False.
  items = pd.read_csv(dataPath + "products.csv", index_col="id")


### Compañia 15

In [3]:
df_pairs = pairs[ pairs.company_id == 15]#.copy()
df_users = users[ users.company_id == 15]#.copy()
df_items = items[ items.company_id == 15]#.copy()

In [4]:
# Comprobacion de que no haya usuarios ni productos duplicados

assert df_users.index.duplicated().any()==False
assert df_items.index.duplicated().any()==False

### Quitar usuarios que interaccionan pero no estan contemplados en la tabla usuarios (unos 575)

In [5]:
usuarios_que_interaccionan_pero_no_en_tabla_usuarios = set(df_pairs.customer_id) - set(df_users.index)
len(usuarios_que_interaccionan_pero_no_en_tabla_usuarios)

575

In [6]:
df_pairs = df_pairs[ ~df_pairs.customer_id.isin(usuarios_que_interaccionan_pero_no_en_tabla_usuarios) ]
len(df_pairs)

59167

### Quitar productos que interaccionan pero no estan contemplados en la tabla productos (unos 162)

In [7]:
productos_que_interaccionan_pero_no_en_tabla_productos = set(df_pairs.product_id) - set(df_items.index)
len(productos_que_interaccionan_pero_no_en_tabla_productos)

162

In [8]:
df_pairs = df_pairs[ ~df_pairs.product_id.isin(productos_que_interaccionan_pero_no_en_tabla_productos) ]
len(df_pairs)

58913

# <center> Fin código limepieza datos
---
# <center> Inicio código Sistema de recomendación

In [9]:
from recommenderSystem2 import RecSys2
r = RecSys2()

In [10]:
r.entrenar_modelo(df_pairs, df_users, df_items)

Leyendo datos...
Entrenando modelo...


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 921/921 [00:16<00:00, 57.37it/s]


tensor(3.0489, grad_fn=<MseLossBackward0>)


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 921/921 [00:15<00:00, 59.74it/s]


tensor(2.5015, grad_fn=<MseLossBackward0>)
Generando embeddings...
Terminado


In [11]:
r.activeUser_ids[:5], r.newUser_ids[:5]

(tensor([21724, 21726, 21728, 21730, 21731]),
 tensor([21725, 21727, 21729, 21742, 21744]))

In [12]:
r.activeItem_ids[:5], r.newItem_ids[:5]

(tensor([28863, 28864, 28865, 28866, 28867]),
 tensor([28871, 28873, 28879, 28881, 28936]))

In [16]:
r.recomendar(query_user_ids=[21724, 21726], searchOn_act_users=True, limit=0.8)

tensor([], dtype=torch.int64)

In [17]:
r.recomendar(query_item_ids=[28863, 28871], searchOn_act_users=True, limit=0.7)

tensor([ 55195,  56453,  51657, 157076,  34875,  50350,  38741,  25184, 171685,
         48278,  34912, 123924,  25527])

In [17]:
r.newUser_embs

tensor([[ 0.3719, -0.0594, -0.3835,  ...,  0.0198,  0.1380,  0.0437],
        [ 0.3719, -0.0594, -0.3835,  ...,  0.0198,  0.1380,  0.0437],
        [ 0.3719, -0.0594, -0.3835,  ...,  0.0198,  0.1380,  0.0437],
        ...,
        [ 0.3719, -0.0594, -0.3835,  ...,  0.0198,  0.1380,  0.0437],
        [ 0.3210, -0.1262, -0.2409,  ..., -0.0244,  0.1400,  0.1837],
        [ 0.3405, -0.0418, -0.3320,  ..., -0.0201,  0.0929,  0.2228]])

In [18]:
r.activeUser_embs

tensor([[ 0.3192, -0.0241, -0.2915,  ..., -0.1165,  0.1095,  0.0411],
        [ 0.3002, -0.0479,  0.0032,  ...,  0.0162,  0.1553, -0.0342],
        [ 0.4004, -0.0542, -0.3557,  ...,  0.0184, -0.0594,  0.2058],
        ...,
        [ 0.2329, -0.1110, -0.2166,  ..., -0.0215,  0.4049,  0.1638],
        [ 0.3030, -0.2221, -0.2273,  ..., -0.0230,  0.1322,  0.1733],
        [ 0.2253, -0.0509, -0.3024,  ...,  0.0155, -0.0522,  0.0342]])

In [19]:
r.activeItem_embs

tensor([[ 0.2910, -0.0460, -0.2071,  ...,  0.0156,  0.7747,  0.0952],
        [ 0.2818, -0.0875, -0.2786,  ..., -0.1080,  0.1367,  0.4187],
        [ 0.2780, -0.0760, -0.2691,  ...,  0.0087,  0.1218,  0.1433],
        ...,
        [ 0.3849, -0.0944, -0.1464,  ...,  0.0619,  0.1363,  0.2019],
        [ 0.0826, -0.0628, -0.2057,  ...,  0.0445,  0.0963,  0.0569],
        [ 0.1099,  0.1584, -0.2032,  ...,  0.0713,  0.0286, -0.1603]])